name: Build

on:
  workflow_dispatch:
    input:
      auto_deploy:
        description: Auto deploy to (NONE/UAT/PRD)
        default: NONE
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i

      - name: Clone UAT repo
        run: git clone --depth 1 https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/uat-railmapgen/rmg-repositories.git

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}

      - name: Auto deploy
        if: ${{ github.event.inputs.auto_deploy == 'PRD' || github.event.inputs.auto_deploy == 'UAT' }}
        run: |
          curl -XPOST -u "wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/uat-railmapgen/rmg-repositories/actions/workflows/release.yml/dispatches \
            --data '{"ref": "master", "inputs": {"app_name": "rmg-components", "version": "${{ github.env.RMG_VER }}", "environment": "${{ github.event.inputs.auto_deploy }}"}}'