name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i

      - name: Clone UAT repo
        run: git clone --depth 1 https://wongchito:${{ secrets.RMG_BUILD_AND_RELEASE }}@github.com/uat-railmapgen/rmg-repositories.git

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Publish
        if: ${{ github.ref == 'refs/heads/master'  }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RMG_NPM_PUBLISH }}